
//! Autogenerated weights for `pallet_game`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-08-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `recrafter-Legion-5-16IRX9`, CPU: `Intel(R) Core(TM) i7-14650HX`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/container-chain-simple-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_game
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/game/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions needed for pallet_game.
pub trait WeightInfo {
	fn setup_game() -> Weight;
	fn register_user() -> Weight;
	fn give_points() -> Weight;
	fn play_game() -> Weight;
	fn submit_answer() -> Weight;
	fn check_result() -> Weight;
	fn list_nft() -> Weight;
	fn delist_nft() -> Weight;
	fn make_offer() -> Weight;
	fn handle_offer() -> Weight;
	fn add_property() -> Weight;
	fn remove_property() -> Weight;
	fn add_to_admins() -> Weight;
	fn remove_from_admins() -> Weight;
	fn request_token() -> Weight;
}

/// Weight functions for `pallet_game`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Nfts::NextCollectionId` (r:1 w:1)
	/// Proof: `Nfts::NextCollectionId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Collection` (r:8 w:8)
	/// Proof: `Nfts::Collection` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::GameProperties` (r:1 w:1)
	/// Proof: `GameModule::GameProperties` (`max_values`: Some(1), `max_size`: Some(50602), added: 51097, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::CurrentRound` (r:1 w:1)
	/// Proof: `GameModule::CurrentRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::RoundActive` (r:0 w:1)
	/// Proof: `GameModule::RoundActive` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::CollectionColor` (r:0 w:8)
	/// Proof: `GameModule::CollectionColor` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionRoleOf` (r:0 w:8)
	/// Proof: `Nfts::CollectionRoleOf` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionConfigOf` (r:0 w:8)
	/// Proof: `Nfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionAccount` (r:0 w:8)
	/// Proof: `Nfts::CollectionAccount` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	fn setup_game() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `272`
		//  Estimated: `52087`
		// Minimum execution time: 168_919_000 picoseconds.
		Weight::from_parts(173_920_000, 0)
			.saturating_add(Weight::from_parts(0, 52087))
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().writes(45))
	}
	/// Storage: `GameModule::Admins` (r:1 w:0)
	/// Proof: `GameModule::Admins` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::Users` (r:1 w:1)
	/// Proof: `GameModule::Users` (`max_values`: None, `max_size`: Some(101), added: 2576, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn register_user() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196`
		//  Estimated: `3593`
		// Minimum execution time: 29_550_000 picoseconds.
		Weight::from_parts(30_570_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `GameModule::Users` (r:1 w:1)
	/// Proof: `GameModule::Users` (`max_values`: None, `max_size`: Some(101), added: 2576, mode: `MaxEncodedLen`)
	fn give_points() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `261`
		//  Estimated: `3566`
		// Minimum execution time: 11_597_000 picoseconds.
		Weight::from_parts(12_100_000, 0)
			.saturating_add(Weight::from_parts(0, 3566))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `GameModule::Users` (r:1 w:0)
	/// Proof: `GameModule::Users` (`max_values`: None, `max_size`: Some(101), added: 2576, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::RoundActive` (r:1 w:0)
	/// Proof: `GameModule::RoundActive` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::CurrentRound` (r:1 w:0)
	/// Proof: `GameModule::CurrentRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::GameId` (r:1 w:1)
	/// Proof: `GameModule::GameId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::GamesExpiring` (r:1 w:1)
	/// Proof: `GameModule::GamesExpiring` (`max_values`: None, `max_size`: Some(822), added: 3297, mode: `MaxEncodedLen`)
	/// Storage: `RandomnessCollectiveFlip::RandomMaterial` (r:1 w:0)
	/// Proof: `RandomnessCollectiveFlip::RandomMaterial` (`max_values`: Some(1), `max_size`: Some(2594), added: 3089, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::GameProperties` (r:1 w:1)
	/// Proof: `GameModule::GameProperties` (`max_values`: Some(1), `max_size`: Some(50602), added: 51097, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::GameInfo` (r:0 w:1)
	/// Proof: `GameModule::GameInfo` (`max_values`: None, `max_size`: Some(564), added: 3039, mode: `MaxEncodedLen`)
	fn play_game() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `617`
		//  Estimated: `52087`
		// Minimum execution time: 31_472_000 picoseconds.
		Weight::from_parts(32_826_000, 0)
			.saturating_add(Weight::from_parts(0, 52087))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `GameModule::GameInfo` (r:1 w:1)
	/// Proof: `GameModule::GameInfo` (`max_values`: None, `max_size`: Some(564), added: 3039, mode: `MaxEncodedLen`)
	fn submit_answer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `378`
		//  Estimated: `4029`
		// Minimum execution time: 12_606_000 picoseconds.
		Weight::from_parts(13_040_000, 0)
			.saturating_add(Weight::from_parts(0, 4029))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `GameModule::GameInfo` (r:1 w:1)
	/// Proof: `GameModule::GameInfo` (`max_values`: None, `max_size`: Some(564), added: 3039, mode: `MaxEncodedLen`)
	/// Storage: `RandomnessCollectiveFlip::RandomMaterial` (r:1 w:0)
	/// Proof: `RandomnessCollectiveFlip::RandomMaterial` (`max_values`: Some(1), `max_size`: Some(2594), added: 3089, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::CurrentRound` (r:1 w:0)
	/// Proof: `GameModule::CurrentRound` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::NextColorId` (r:1 w:1)
	/// Proof: `GameModule::NextColorId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Item` (r:1 w:1)
	/// Proof: `Nfts::Item` (`max_values`: None, `max_size`: Some(861), added: 3336, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Collection` (r:1 w:1)
	/// Proof: `Nfts::Collection` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionConfigOf` (r:1 w:0)
	/// Proof: `Nfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemConfigOf` (r:1 w:1)
	/// Proof: `Nfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionRoleOf` (r:1 w:0)
	/// Proof: `Nfts::CollectionRoleOf` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::Users` (r:1 w:1)
	/// Proof: `GameModule::Users` (`max_values`: None, `max_size`: Some(101), added: 2576, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::CollectionColor` (r:1 w:0)
	/// Proof: `GameModule::CollectionColor` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::Leaderboard` (r:1 w:1)
	/// Proof: `GameModule::Leaderboard` (`max_values`: Some(1), `max_size`: Some(361), added: 856, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Account` (r:0 w:1)
	/// Proof: `Nfts::Account` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn check_result() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1823`
		//  Estimated: `4326`
		// Minimum execution time: 74_380_000 picoseconds.
		Weight::from_parts(77_352_000, 0)
			.saturating_add(Weight::from_parts(0, 4326))
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `Nfts::Item` (r:1 w:1)
	/// Proof: `Nfts::Item` (`max_values`: None, `max_size`: Some(861), added: 3336, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionRoleOf` (r:1 w:0)
	/// Proof: `Nfts::CollectionRoleOf` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemConfigOf` (r:1 w:1)
	/// Proof: `Nfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Collection` (r:1 w:0)
	/// Proof: `Nfts::Collection` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Attribute` (r:1 w:0)
	/// Proof: `Nfts::Attribute` (`max_values`: None, `max_size`: Some(446), added: 2921, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionConfigOf` (r:1 w:0)
	/// Proof: `Nfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::NextListingId` (r:1 w:1)
	/// Proof: `GameModule::NextListingId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::Listings` (r:0 w:1)
	/// Proof: `GameModule::Listings` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Account` (r:0 w:2)
	/// Proof: `Nfts::Account` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemPriceOf` (r:0 w:1)
	/// Proof: `Nfts::ItemPriceOf` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::PendingSwapOf` (r:0 w:1)
	/// Proof: `Nfts::PendingSwapOf` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	fn list_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1444`
		//  Estimated: `4326`
		// Minimum execution time: 67_297_000 picoseconds.
		Weight::from_parts(69_092_000, 0)
			.saturating_add(Weight::from_parts(0, 4326))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `GameModule::Listings` (r:1 w:1)
	/// Proof: `GameModule::Listings` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Collection` (r:1 w:0)
	/// Proof: `Nfts::Collection` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Attribute` (r:1 w:0)
	/// Proof: `Nfts::Attribute` (`max_values`: None, `max_size`: Some(446), added: 2921, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionConfigOf` (r:1 w:0)
	/// Proof: `Nfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemConfigOf` (r:1 w:1)
	/// Proof: `Nfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Item` (r:1 w:1)
	/// Proof: `Nfts::Item` (`max_values`: None, `max_size`: Some(861), added: 3336, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionRoleOf` (r:1 w:0)
	/// Proof: `Nfts::CollectionRoleOf` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Account` (r:0 w:2)
	/// Proof: `Nfts::Account` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemPriceOf` (r:0 w:1)
	/// Proof: `Nfts::ItemPriceOf` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::PendingSwapOf` (r:0 w:1)
	/// Proof: `Nfts::PendingSwapOf` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	fn delist_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1541`
		//  Estimated: `4326`
		// Minimum execution time: 63_138_000 picoseconds.
		Weight::from_parts(64_639_000, 0)
			.saturating_add(Weight::from_parts(0, 4326))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `GameModule::Listings` (r:1 w:0)
	/// Proof: `GameModule::Listings` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionRoleOf` (r:1 w:0)
	/// Proof: `Nfts::CollectionRoleOf` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemConfigOf` (r:1 w:1)
	/// Proof: `Nfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Collection` (r:1 w:0)
	/// Proof: `Nfts::Collection` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Attribute` (r:1 w:0)
	/// Proof: `Nfts::Attribute` (`max_values`: None, `max_size`: Some(446), added: 2921, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionConfigOf` (r:1 w:0)
	/// Proof: `Nfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Item` (r:1 w:1)
	/// Proof: `Nfts::Item` (`max_values`: None, `max_size`: Some(861), added: 3336, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::NextOfferId` (r:1 w:1)
	/// Proof: `GameModule::NextOfferId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::Offers` (r:0 w:1)
	/// Proof: `GameModule::Offers` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Account` (r:0 w:2)
	/// Proof: `Nfts::Account` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemPriceOf` (r:0 w:1)
	/// Proof: `Nfts::ItemPriceOf` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::PendingSwapOf` (r:0 w:1)
	/// Proof: `Nfts::PendingSwapOf` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	fn make_offer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1615`
		//  Estimated: `4326`
		// Minimum execution time: 69_554_000 picoseconds.
		Weight::from_parts(71_764_000, 0)
			.saturating_add(Weight::from_parts(0, 4326))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `GameModule::Offers` (r:1 w:1)
	/// Proof: `GameModule::Offers` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::Listings` (r:1 w:1)
	/// Proof: `GameModule::Listings` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Collection` (r:1 w:0)
	/// Proof: `Nfts::Collection` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Attribute` (r:2 w:0)
	/// Proof: `Nfts::Attribute` (`max_values`: None, `max_size`: Some(446), added: 2921, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionConfigOf` (r:1 w:0)
	/// Proof: `Nfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemConfigOf` (r:2 w:2)
	/// Proof: `Nfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Item` (r:2 w:2)
	/// Proof: `Nfts::Item` (`max_values`: None, `max_size`: Some(861), added: 3336, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionRoleOf` (r:1 w:0)
	/// Proof: `Nfts::CollectionRoleOf` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::Users` (r:2 w:2)
	/// Proof: `GameModule::Users` (`max_values`: None, `max_size`: Some(101), added: 2576, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::CollectionColor` (r:1 w:0)
	/// Proof: `GameModule::CollectionColor` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `GameModule::Leaderboard` (r:1 w:1)
	/// Proof: `GameModule::Leaderboard` (`max_values`: Some(1), `max_size`: Some(361), added: 856, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Account` (r:0 w:4)
	/// Proof: `Nfts::Account` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemPriceOf` (r:0 w:2)
	/// Proof: `Nfts::ItemPriceOf` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::PendingSwapOf` (r:0 w:2)
	/// Proof: `Nfts::PendingSwapOf` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	fn handle_offer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2243`
		//  Estimated: `7662`
		// Minimum execution time: 128_987_000 picoseconds.
		Weight::from_parts(132_519_000, 0)
			.saturating_add(Weight::from_parts(0, 7662))
			.saturating_add(T::DbWeight::get().reads(15))
			.saturating_add(T::DbWeight::get().writes(17))
	}
	/// Storage: `GameModule::GameProperties` (r:1 w:1)
	/// Proof: `GameModule::GameProperties` (`max_values`: Some(1), `max_size`: Some(50602), added: 51097, mode: `MaxEncodedLen`)
	fn add_property() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `52087`
		// Minimum execution time: 7_293_000 picoseconds.
		Weight::from_parts(7_667_000, 0)
			.saturating_add(Weight::from_parts(0, 52087))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `GameModule::GameProperties` (r:1 w:1)
	/// Proof: `GameModule::GameProperties` (`max_values`: Some(1), `max_size`: Some(50602), added: 51097, mode: `MaxEncodedLen`)
	fn remove_property() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `52087`
		// Minimum execution time: 8_061_000 picoseconds.
		Weight::from_parts(8_466_000, 0)
			.saturating_add(Weight::from_parts(0, 52087))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `GameModule::Admins` (r:1 w:1)
	/// Proof: `GameModule::Admins` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	fn add_to_admins() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `155`
		//  Estimated: `1806`
		// Minimum execution time: 9_362_000 picoseconds.
		Weight::from_parts(9_657_000, 0)
			.saturating_add(Weight::from_parts(0, 1806))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `GameModule::Admins` (r:1 w:1)
	/// Proof: `GameModule::Admins` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	fn remove_from_admins() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196`
		//  Estimated: `1806`
		// Minimum execution time: 10_776_000 picoseconds.
		Weight::from_parts(11_273_000, 0)
			.saturating_add(Weight::from_parts(0, 1806))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `GameModule::Users` (r:1 w:1)
	/// Proof: `GameModule::Users` (`max_values`: None, `max_size`: Some(101), added: 2576, mode: `MaxEncodedLen`)
	fn request_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `261`
		//  Estimated: `3566`
		// Minimum execution time: 38_404_000 picoseconds.
		Weight::from_parts(41_354_000, 0)
			.saturating_add(Weight::from_parts(0, 3566))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
